name: "Ansible Check (Lint + Local)"

on:
  pull_request: # This will run on PRs to validate Ansible code before merging
  workflow_dispatch:  # This enables the "Run workflow" button in the UI

jobs:
  check:
    uses: Infra/reusable-workflows-vault/.gitea/workflows/reusable-ansible-check.yml@main
    with:
      ansible_playbook_path: "ansible/playbook.yml"
            